## © 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0
---
- name: Stop gitea container
  docker_container:
    name: gitea
    state: stopped
- name: Remove gitea container
  docker_container:
    name: gitea
    state: absent
- name: Recursively remove gitea directory
  ansible.builtin.file:
    path: /home/{{ cloud_user }}/gitea
    state: absent
